# Load config
if "--configfile" in sys.argv:
    i = sys.argv.index("--configfile")
    config_path = sys.argv[i + 1]
    configfile: config_path
else:
    config_path = "config/config.yaml"
    configfile: config_path

DATA_DIR = config["DATA_DIR"]
RESULTS_DIR = config["RESULTS_DIR"]
LOGS_DIR = config["LOGS_DIR"]

SAMPLES = config["SAMPLES"]

rule all:
    input:
        os.path.join(RESULTS_DIR, "fastqc", sample, sample_reads, sample_reads+"_fastqc.html") for sample in SAMPLES.keys() for sample_reads in SAMPLES[sample]["reads"]

rule FastQC:
    input:
        os.path.join(DATA_DIR, "{sample}", "{sample_reads}.fastq.gz")
    output:
        os.path.join(RESULTS_DIR, "fastqc", "{sample}", "{sample_reads}", "{sample_reads}_fastqc.html")
    params:
        out_dir=os.path.join(RESULTS_DIR, "fastqc", "{sample}", "{sample_reads}")
    log:
        os.path.join(LOGS_DIR, "fastqc", "{sample}", "{sample_reads}.log")
    conda:
        "envs/fastqc.yaml"
    shell:
        """
        mkdir -p {params.out_dir}
        fastqc {input} --outdir {params.out_dir} > {log} 2>&1
        """