RESOURCES_DIR: resources/
DATA_DIR: data/
RESULTS_DIR: results/
LOGS_DIR: logs/

SAMPLES:
  # 011425_MiSeq:
  #   reads:
  #     - 000000000-GP7HJ_Undetermined_S0_L001_R1_001
  #     - 000000000-GP7HJ_Undetermined_S0_L001_R2_001
  #     - 000000000-GP7HJ_Undetermined_S0_L001_R3_001
  061324_MiSeq:
    reads: 000000000-GLTD9_Undetermined_S0_L001_R1_001
    index: 000000000-GLTD9_Undetermined_S0_L001_R2_001
    index_seqs: 
      - AGTCAA
      - AGTTCC
    max_hamming: 1
  # 082224_MiSeq:
  #   reads: 000000000-GM5RM_Undetermined_S0_L001_R1_001
  #   index: 000000000-GM5RM_Undetermined_S0_L001_R2_001
  #   index_seqs: 
  #     - AGTTCC
  #     - AGTCAA
  # 110724_MiSeq:
  #   reads:
  #   - 000000000-GNHNL_Undetermined_S0_L001_R1_001
  #   - 000000000-GNHNL_Undetermined_S0_L001_R2_001
  # 112224_MiSeq:
  #   reads:
  #     - Undetermined_S0_L001_R1_001
  # 121924_MiSeq:
  #   reads:
  #     - Undetermined_S0_L001_R1_001

#CLIP:
samples: "config/samples.tsv"

SHELL_EXEC:
  "/bin/bash"

## Reference genome and annotation:
REFERENCE_GENOME:
  "chr1.fa"
GFF:
  "gencode.v19.annotation.gff3"
GTF:
  "gencode.v19.annotation.gtf"

## UMIs if present:
UMI-BARCODE:
  "NNNNNNNNNN"

## All possible CLIP adapter sequences:
THREE_PRIME_ADAPTER_SEQUENCE:
  "TGGAATTCTCGGGTGCCAAGG"
FIVE_PRIME_ADAPTER_SEQUENCE:
  "AATGATACGGCGACCACCGACAGGTTCAGAGTTCTACAGTCCGACGATC"
NINETEEN_NUCLEOTIDE_MARKER_SEQUENCE:
  "CGTACGCGGGTTTAAACGA"
TWENTY_FOUR_NUCLEOTIDE_MARKER_SEQUENCE:
  "CGTACGCGGAATAGTTTAAACTGT"
ICLIP_ADAPTER:
  "AGATCGGAAGAGCGGTTCAG"
HITSCLIP_3ADAPTER:
  "TCGTATGCCGTCTTCTGCTTG"
HITSCLIP_5ADAPTER:
  "AATGATACGGCGACCACCGA"
KIT_5ADAPTER:
  "GTTCAGAGTTCTACAGTCCGACGATC"
SPECIAL_AD_1:
  "AGATCGGAAGAGCACACGTCTG"
SPECIAL_AD_2:
  "CTCGTATGCCGTCTTCTGCTTG"
SPECIAL_AD_3:
  "TGAGATCGGAAGAGCGGTTCAG"

## Number of threads:
THR:
  8

## RNA-seq background for omniCLIP:
BACKGROUND:
  "test_data/test_backgr.bam"

## omniCLIP settings
MAX_IT: 10

## PARALYZER settings:
call_peaks:
  BANDWIDTH: 3
  CONVERSION: T>C
  MINIMUM_READ_COUNT_PER_GROUP: 5
  MINIMUM_READ_COUNT_PER_CLUSTER: 5
  MINIMUM_READ_COUNT_FOR_KDE: 5
  MINIMUM_CLUSTER_SIZE: 8
  MINIMUM_CONVERSION_LOCATIONS_FOR_CLUSTER: 1
  MINIMUM_CONVERSION_COUNT_FOR_CLUSTER: 1
  MINIMUM_READ_COUNT_FOR_CLUSTER_INCLUSION: 5
  MINIMUM_READ_LENGTH: 13
  MAXIMUM_NUMBER_OF_NON_CONVERSION_MISMATCHES: 0

  OUTPUT_DISTRIBUTIONS_FILE: ".distribution"
  OUTPUT_GROUPS_FILE: ".groups"
  OUTPUT_CLUSTERS_FILE: ".clusters"
  OUTPUT_READS_FILE: "_PARalyzer_Utilized.sam"

  EXTEND_BY_READ: True
  HAFFNER_APPROACH: False
  ADDITIONAL_NUCLEOTIDES_BEYOND_SIGNAL: 0